version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_consultoria
    restart: always
    environment:
      MYSQL_DATABASE: sistema_consultoria
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend-api:
    build: .
    container_name: api_consultoria
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sistema_consultoria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Instrução para o Hibernate criar as tabelas no MySQL zerado do Docker:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: